name = "Permutations"
uuid = "2ae35dd2-176d-5d53-8349-f30d82d94d4f"
author = ["Edward Scheinerman <ers@jhu.edu>"]
version = "0.4.22"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Combinatorics = "1"
julia = "1"
LinearAlgebra = "1"
Random = "1"
